version: 2
jobs:
  test:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - run:
          name: Build debug APK
          command: |
            ./gradlew :app:testDebugUnitTest
            ./gradlew :app:assembleDebugAndroidTest